# Generated by Django 5.2.7 on 2025-11-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Properties', '0001_initial'),
        ('Tenants', '0002_myrentaldetails_delete_tenantprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myrentaldetails',
            name='property',
        ),
        migrations.AddField(
            model_name='myrentaldetails',
            name='property',
            field=models.ManyToManyField(blank=True, null=True, to='Properties.property'),
        ),
    ]
