# Generated by Django 5.2.7 on 2025-11-10 17:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Properties', '0001_initial'),
        ('Tenants', '0003_remove_myrentaldetails_property_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyRentalDetails',
            new_name='MyRentalDetail',
        ),
    ]
