# Generated by Django 5.2.7 on 2025-11-11 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Properties', '0001_initial'),
        ('Tenants', '0004_rename_myrentaldetails_myrentaldetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myrentaldetail',
            name='property',
        ),
        migrations.AddField(
            model_name='myrentaldetail',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Properties.property'),
        ),
    ]
