# Generated by Django 5.2.7 on 2025-11-20 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0003_alter_payment_payment_method_delete_paymentmethod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='note',
        ),
    ]
