# Generated by Django 5.2.7 on 2025-11-26 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0005_alter_payment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_date',
            new_name='payment_date_time',
        ),
    ]
