# Generated by Django 5.2.7 on 2025-12-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0006_rename_payment_date_payment_payment_date_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_date_time',
            new_name='payment_date',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_time',
            field=models.TimeField(default=None),
        ),
    ]
