# Generated by Django 5.2.7 on 2025-12-04 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0007_rename_payment_date_time_payment_payment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_time',
            field=models.TimeField(default=datetime.datetime(2025, 12, 4, 20, 36, 2, 58625)),
        ),
    ]
