# Generated by Django 5.2.7 on 2025-12-04 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0008_alter_payment_payment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_time',
            field=models.TimeField(default=datetime.time(20, 37, 59, 253313)),
        ),
    ]
