# Generated by Django 5.2.7 on 2025-12-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0012_alter_payment_payment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
