# Generated by Django 5.2.7 on 2025-11-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_rename_customuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='ph_no',
            field=models.CharField(blank=True, null=True),
        ),
    ]
