# Generated by Django 5.2.7 on 2025-11-06 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='full_name',
        ),
    ]
