# Generated by Django 5.2.7 on 2025-11-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_rename_name_user_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='Unknown', max_length=20),
        ),
    ]
