# Generated by Django 5.2.7 on 2025-11-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0008_alter_user_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('company_admin', 'Company Admin'), ('tenant', 'Tenant')], default='tenant', max_length=20),
        ),
    ]
